name: Cypress Testing
on: [push]
jobs:
  run-test:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies in client
        run: npm install
        working-directory: client
      - name: Run test
        uses: cypress-io/github-action@v4.2.0
        with:
          working-directory: client
          start: npm start
          wait-on: "http://localhost:3000"
          browser: chrome
