name: MochaJS Testing
on: [push]
jobs:
  test:
    name: 'Node.js v${{ matrix.node }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
        working-directory: server
      - name: Install MochaJS
        run: npm install mocha -g
        working-directory: server
      - name: Run MochaJS tests
        run: npm test
        working-directory: server
