name: MochaJS Testing
env:
  PORT: ${{secrets.PORT}}
  CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
  CLOUDINARY_API_SECRET: ${{secrets.CLOUDINARY_API_SECRET}}
  CLOUDINARY_NAME: ${{secrets.CLOUDINARY_NAME}}
  DATABASE_ACCESS: ${{secrets.DATABASE_ACCESS}}
  PASSPORT_KEY: ${{secrets.PASSPORT_KEY}}
  EMAIL: ${{secrets.EMAIL}}
  EMAIL_PWD: ${{secrets.EMAIL_PWD}}
  SERVER_URL: ${{secrets.SERVER_URL}}
on: [push]
jobs:
  test:
    name: 'Node.js v${{ matrix.node }}'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
        working-directory: server
      - name: Install MochaJS
        run: npm install mocha -g
        working-directory: server
      - name: Run Mocha Tests (mochaJS)
        run: npm test
        working-directory: server
